### ISSUE TITLE
Launch Voltaire DevNet

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-world#82]
Launch a community devnet for voltaire. Provide half of supply to CF so they can participate in running it as well. Provide faucet to community for delegation. Establish process for notifying community 24 hours in advance of network resets to adopt new features.
# Phase 1

- [x] Integrate Conway era into node
- [ ] Design Governance CLI commands
- [ ] Obtain Feedback on CLI commands from users
- [ ] Design user acceptance tests for CLI commands
- [ ] Implement first governance action submission and enactment in ledger, integrate into node and test
- [ ] Implement first set of Governance CLI commands, test and deploy
- [ ] Establish Initial DevNet
- [ ] Communicate to SPOs
- [ ] Integrate additional governance actions into ledger, test, and deploy to devnet
- [ ] Implement CC voting and ratification
- [ ] Test CC operation with users
- [ ] Determine initial threshold and governance parameter settings
- [ ] Test governance parameter and threshold settings with users and adjust as necessary
- [ ] Implement SPO voting and update enactment process
- [ ] Test hard fork enactment (to broken non-existent future era)
- [ ] Expose ledger state for external use

# Phase 2
- [ ] Implement DRep Delegation map
- [ ] Implement DRep registration and retirement
- [ ] Implement DRep delegation certificates
- [ ] Implement DRep voting
- [ ] Update ratification process to include DReps
- [ ] Test DRep delegation, voting and confirm correct action enactment
- [ ] Respin devnet as each new feature set is added
-[ ] Document CLI commands
- [ ] Develop Tutorials and Exercises for CLI commands
- [ ] Test DRep delegation, voting and confirm correct action enactment
- [ ] Design extended DB-Sync schema
- [ ] Deploy DB-Sync instance on Devnet to support voting app
- [ ] Extend DB-Sync to include new ledger state (incrementally)
- [ ] Synchronise other teams including community members DB-Sync/voting tooling
- [ ] Design extended DB-Sync schema
- [ ] Deploy DB-Sync instance on Devnet
- [ ] Extend DB-Sync to include new ledger state (incrementally)
